name: Update drops list

on:
  schedule:
    - cron: '15 0 * * *'
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master branch
      uses: actions/checkout@v4
      with:
        ref: 'master'
    
    - name: Install rust toolchain
      uses: dtolnay/rust-toolchain@stable
    
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Update drops list
      run: cargo run
    
    - name: Checkout drops branch
      uses: actions/checkout@v4
      with:
        ref: 'drops'
        path: drops-branch
    
    - name: Update list on drops branch
      run: |
        mv ./DROPS.md ./drops-branch/README.md
        cd drops-branch
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add README.md
        git diff --cached --quiet || (
          git commit -m "docs: update drops list"
          git push origin drops
        )
