name: Rust

on:
  schedule:
    - cron: '15 0 * * *'
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Update README.md
      run: cargo run

    - name: Commit and push update
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add -f README.md
        git commit -m "docs: update drops list [skip ci]"
        git push
